# Funding options for liblloyal
# Display a "Sponsor" button in the repository

# Uncomment and add your funding platforms:
# github: [lloyal-ai]
# patreon: username
# ko_fi: username
# custom: ["https://lloyal.ai/sponsor", "https://example.com"]
